### ISSUE TITLE
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

### ISSUE THREAD

**Issue by Ramen5914** [carlosascari/2xBR-Filter#4]
When running the html file (example.html) you get the following error: "Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data."

**Comment by lostrepo** [comment]
@OmarRahmanK You should use server to avoid such CORS issues.
Don't forget to close issue.
